In [113]:
import numpy as np

In [114]:
from pyscf import gto, scf, df

In [740]:
#mol = gto.M(atom='H 0 0 0; H 0 0 0.740848149', basis='STO-3G', charge = 0)
mol = gto.M(atom='He 0 0 0; H 0 0 1', basis='STO-3G', charge = 1)


In [710]:
#get one elctron integrals

overlap_integrals = mol.intor('int1e_ovlp_sph')
print("overlap_integrals")
print(overlap_integrals)

kinetic_energy_integrals = mol.intor('int1e_kin_sph')
print("kinetic_energy_integrals")
print(kinetic_energy_integrals)

nuclear_attraction_integrals = mol.intor('int1e_nuc_sph')
print("nuclear_attraction_integrals")
print(nuclear_attraction_integrals)


overlap_integrals
[[ 1.00000000e+00  6.34151770e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.97046603e-01  2.57117843e-01  0.00000000e+00
   0.00000000e+00 -3.11560223e-01]
 [ 6.34151770e-01  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  4.71635500e-01  6.35457169e-01  0.00000000e+00
   0.00000000e+00 -3.54130850e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  2.01358561e-01
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.01358561e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  3.32049288e-01  1.36861980e-01  0.00000000e+00
   0.00000000e+00 -4.37809862e-01]
 [ 1.97046603e-01  4.71635500e-01  0.00000000e+00  0.00000000e+00
   3.32049288e-01  1.00000000e+00  6.84799825e-01  0.00000000e+00
   0.00000000e+

In [711]:
#get two electron integrals

two_electron_integrals = mol.intor('int2e_sph')
print("two_electron_integrals")
print(two_electron_integrals)

two_electron_integrals
[[[[ 1.54302122  0.78494872  0.         ...  0.          0.
    -0.37791494]
   [ 0.78494872  0.80343421  0.         ...  0.          0.
    -0.34214293]
   [ 0.          0.          0.99714929 ...  0.15847115  0.
    -0.        ]
   ...
   [ 0.          0.          0.15847115 ...  0.48221423  0.
    -0.        ]
   [ 0.          0.          0.         ...  0.          0.48221423
    -0.        ]
   [-0.37791494 -0.34214293 -0.         ... -0.         -0.
     0.59686842]]

  [[ 0.78494872  0.42674586  0.         ...  0.          0.
    -0.2071906 ]
   [ 0.42674586  0.47588057  0.         ...  0.          0.
    -0.20090556]
   [ 0.          0.          0.58116666 ...  0.09607534  0.
    -0.        ]
   ...
   [ 0.          0.          0.09607534 ...  0.30433865  0.
    -0.        ]
   [ 0.          0.          0.         ...  0.          0.30433865
    -0.        ]
   [-0.2071906  -0.20090556 -0.         ... -0.         -0.
     0.36444878]]

  [[ 0.          0.

In [712]:
#calculate core hamiltonian

H_core = kinetic_energy_integrals + nuclear_attraction_integrals
H_core

array([[-2.40943417, -1.88105429,  0.        ,  0.        , -0.104692  ,
        -0.68935843, -0.83824067,  0.        ,  0.        ,  0.96009771],
       [-1.88105429, -1.8030552 ,  0.        ,  0.        , -0.1620693 ,
        -0.98199941, -1.13017774,  0.        ,  0.        ,  0.7427404 ],
       [ 0.        ,  0.        , -0.11983422,  0.        ,  0.        ,
         0.        ,  0.        , -0.30982452,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.11983422,  0.        ,
         0.        ,  0.        ,  0.        , -0.30982452,  0.        ],
       [-0.104692  , -0.1620693 ,  0.        ,  0.        , -0.2294278 ,
        -0.6606273 , -0.32825384,  0.        ,  0.        ,  0.30682158],
       [-0.68935843, -0.98199941,  0.        ,  0.        , -0.6606273 ,
        -1.45858699, -1.14475207,  0.        ,  0.        ,  0.33498563],
       [-0.83824067, -1.13017774,  0.        ,  0.        , -0.32825384,
        -1.14475207, -1.23489652,  0.        

In [713]:
#diagonalize overlap integral matrix

overlap_diag_procedure = np.linalg.eig(overlap_integrals)
overlap_diag_procedure

(array([2.60693649, 0.15276413, 0.26222897, 0.45386006, 1.33567544,
        1.18853491, 0.79864144, 1.20135856, 1.20135856, 0.79864144]),
 array([[-3.95686695e-01, -2.48594694e-01,  1.21657397e-01,
         -6.74444631e-01, -9.37862014e-02, -5.50600384e-01,
         -1.53919880e-16,  4.88789465e-15, -2.05616933e-15,
          7.50139257e-17],
        [-5.38993792e-01,  7.21680922e-01, -4.39450360e-02,
          2.86562859e-01,  8.12695625e-02, -3.13062549e-01,
         -2.28223866e-17,  2.73511642e-15, -1.06741673e-15,
          8.73187705e-17],
        [-4.04481703e-17, -3.13128518e-17, -2.06760887e-16,
          1.24725761e-16, -8.77120198e-16, -6.36910449e-15,
         -7.02551555e-01, -6.96471033e-01, -2.62928084e-02,
         -7.32169446e-02],
        [-3.06536374e-19,  6.18365453e-17,  1.70170857e-16,
         -7.11213296e-18,  6.54950332e-16,  1.04186484e-15,
          8.01330913e-02,  1.22180604e-01, -7.06617781e-01,
         -7.03305964e-01],
        [-2.04560088e-01,  3.12464

In [714]:
#diagonalize overlap integral matrix

U = overlap_diag_procedure[1]
print(U)

#print(np.matmul(overlap_integrals,U))
#print(np.matrix.transpose(U))

#rint("---------------")

# = np.matmul(np.matrix.transpose(U),np.matmul(overlap_integrals,U))
#print(s)

s_inverse = np.diag(1/overlap_diag_procedure[0])
s_inverse

[[-3.95686695e-01 -2.48594694e-01  1.21657397e-01 -6.74444631e-01
  -9.37862014e-02 -5.50600384e-01 -1.53919880e-16  4.88789465e-15
  -2.05616933e-15  7.50139257e-17]
 [-5.38993792e-01  7.21680922e-01 -4.39450360e-02  2.86562859e-01
   8.12695625e-02 -3.13062549e-01 -2.28223866e-17  2.73511642e-15
  -1.06741673e-15  8.73187705e-17]
 [-4.04481703e-17 -3.13128518e-17 -2.06760887e-16  1.24725761e-16
  -8.77120198e-16 -6.36910449e-15 -7.02551555e-01 -6.96471033e-01
  -2.62928084e-02 -7.32169446e-02]
 [-3.06536374e-19  6.18365453e-17  1.70170857e-16 -7.11213296e-18
   6.54950332e-16  1.04186484e-15  8.01330913e-02  1.22180604e-01
  -7.06617781e-01 -7.03305964e-01]
 [-2.04560088e-01  3.12464983e-01  3.44398360e-01 -3.30900443e-01
  -5.44047600e-01  5.80023862e-01  1.66528093e-16 -4.80827064e-15
   1.85808552e-15  1.52523209e-17]
 [-4.57261851e-01 -1.41505874e-01 -6.92568695e-01 -1.97505920e-01
   2.41710384e-01  4.40231520e-01  2.11341811e-16 -3.89459644e-15
   1.73278599e-15 -4.19668044e-17

array([[0.38359201, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 6.5460391 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 3.81346122, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.20332231, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.74868487,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.84137201, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.25212636, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [715]:
#take square root of diagonalized overlap integral matrix

s_inverse_sqrt = s_inverse**0.5
s_inverse_sqrt

array([[0.61934805, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.55852284, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.95280855, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.48435923, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.86526578,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.91726333, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.11898452, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [716]:
#obtain transformation matrix X

test = np.matmul(s_inverse_sqrt,np.matrix.transpose(U))
print(test)
X = np.matmul(U,np.matmul(s_inverse_sqrt,np.matrix.transpose(U)))
print(X)

[[-2.45067783e-01 -3.33824754e-01 -2.50514954e-17 -1.89852705e-19
  -1.26693892e-01 -2.83204236e-01 -3.02700464e-01 -3.04498274e-18
   2.65730495e-20  1.55599710e-01]
 [-6.36035202e-01  1.84643712e+00 -8.01146463e-17  1.58210213e-16
   7.99448794e-01 -3.62046010e-01 -1.02838046e+00  2.01216981e-17
  -5.07283173e-17  9.51002755e-01]
 [ 2.37573605e-01 -8.58162419e-02 -4.03764427e-16  3.32311105e-16
   6.72544061e-01 -1.35245407e+00  1.12170673e+00  8.45164597e-17
  -1.13296727e-16  4.58238010e-01]
 [-1.00111811e+00  4.25362223e-01  1.85137834e-16 -1.05569602e-17
  -4.91175125e-01 -2.93169735e-01  4.67081091e-01 -7.51548574e-17
   6.28343908e-18 -6.89046861e-01]
 [-8.11499909e-02  7.03197716e-02 -7.58942094e-16  5.66706111e-16
  -4.70745772e-01  2.09143724e-01  3.05695522e-01 -4.67500684e-16
   2.74165921e-16  6.15111576e-01]
 [-5.05045539e-01 -2.87160795e-01 -5.84214596e-15  9.55664411e-16
   5.32034617e-01  4.03808228e-01  1.96295265e-01 -6.24033509e-15
   1.04622970e-15  1.38513320e-01

In [717]:
#recheck XtrSX - works OK
test = np.matmul(np.matrix.transpose(X),np.matmul(overlap_integrals,X))
test

array([[ 1.00000000e+00, -1.14401422e-15,  2.92791970e-16,
         2.71327236e-15, -9.78682520e-17, -3.36776728e-17,
         1.31991009e-16,  5.71990815e-16,  2.90520055e-15,
        -6.93889390e-16],
       [-9.34641429e-16,  1.00000000e+00,  1.40236477e-16,
         1.66655936e-15,  5.60517042e-16, -1.99027732e-16,
        -1.46599175e-16,  2.52612567e-16,  1.60171370e-15,
         1.60288449e-15],
       [ 2.92791970e-16,  1.40236477e-16,  9.78707847e-01,
        -1.42639999e-01, -3.99300775e-16, -3.62587726e-16,
        -2.50679061e-16, -1.71465900e-02, -1.23425143e-01,
        -6.31962700e-16],
       [ 2.71327236e-15,  1.66655936e-15, -1.42639999e-01,
         1.03989736e+00, -2.91849351e-15, -2.47520184e-15,
        -7.90007373e-16, -1.23425143e-01,  3.55581973e-02,
        -7.23967609e-16],
       [-9.09057468e-17,  7.03399249e-16, -3.99300775e-16,
        -2.91849351e-15,  1.00000000e+00, -4.33997442e-16,
         1.34647449e-17, -1.98593208e-16, -2.90597128e-15,
         8.

In [718]:
#intitial guess for density matrix

P = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))
P

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [733]:
# calculate G matrix

G = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))

#for i in range(0,two_electron_integrals.shape[0]):
#    for j in range(0,two_electron_integrals.shape[1]):
#        for k in range(0,two_electron_integrals.shape[2]):
#            for l in range(0,two_electron_integrals.shape[3]):
#                print(two_electron_integrals[i,j,k,l])

#print("-------------")
                
                
for i in range(0,two_electron_integrals.shape[0]):
    for j in range(0,two_electron_integrals.shape[1]):
        for k in range(0,two_electron_integrals.shape[2]):
            for l in range(0,two_electron_integrals.shape[3]):
                G[i,j]+=P[k,l]*(two_electron_integrals[i,j,k,l]-0.5*two_electron_integrals[i,l,k,j])
#print(G)

F = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))
F = H_core + G
print(F)

[[-1.08204360e+00 -1.33013238e+00 -1.16253412e-16 -7.03418256e-16
  -1.40358302e-01 -6.25463932e-01 -6.94416180e-01 -1.74454853e-16
  -8.62286813e-16  6.84690056e-01]
 [-1.33013238e+00 -9.34345491e-01 -6.86289520e-17 -4.17295356e-16
  -1.83249749e-01 -6.27613457e-01 -6.34773786e-01 -1.30616683e-16
  -6.26437374e-16  4.00438058e-01]
 [-1.16253412e-16 -6.86289520e-17  1.48202996e+00 -2.91612431e-31
  -1.51357463e-17 -6.12389704e-17 -4.84213586e-17 -3.61942375e-02
  -2.80007465e-31  4.07496804e-17]
 [-7.03418256e-16 -4.17295356e-16 -2.91612431e-31  1.48202996e+00
  -9.23662911e-17 -3.56700739e-16 -2.86631738e-16 -3.31657458e-31
  -3.61942375e-02  2.49243104e-16]
 [-1.40358302e-01 -1.83249749e-01 -1.51357463e-17 -9.23662911e-17
   1.36747835e+00 -2.37642498e-01 -1.68440851e-01 -2.24025908e-17
  -8.73057489e-17 -3.56748431e-01]
 [-6.25463932e-01 -6.27613457e-01 -6.12389704e-17 -3.56700739e-16
  -2.37642498e-01 -5.38425231e-01 -6.02915187e-01 -4.18896650e-17
  -1.71993701e-16  2.10132880e-01

In [734]:
F_prime = np.matmul(np.matrix.transpose(X),np.matmul(F,X))
F_prime

array([[-2.60753726e-01, -1.08771824e+00, -2.65147354e-16,
        -7.03562882e-17,  2.17746761e-02, -2.55779496e-01,
        -1.65934330e-01, -1.65469452e-16, -6.17304575e-16,
         5.53747557e-01],
       [-1.08771824e+00,  2.51561131e-01, -3.19918344e-16,
        -4.03132300e-16,  3.28700698e-01, -3.41952362e-01,
        -2.43035617e-01, -3.50496280e-16, -1.28289801e-15,
         4.72225674e-01],
       [-2.65147354e-16, -3.19918344e-16,  1.51870696e+00,
        -1.82906651e-01, -6.78909511e-16,  4.40624724e-17,
         2.23809174e-18, -3.23617315e-01, -1.22242820e-01,
        -7.93627316e-16],
       [-7.03562882e-17, -4.03132300e-16, -1.82906651e-01,
         1.59724431e+00, -3.73056610e-15, -1.41518055e-15,
        -3.02145003e-16, -1.22246318e-01, -2.71502527e-01,
        -1.54328919e-16],
       [ 2.17746761e-02,  3.28700698e-01, -6.78909511e-16,
        -3.73056610e-15,  1.95713427e+00, -6.58817540e-01,
        -1.08621429e-01, -1.31907756e-16, -3.29227039e-15,
         5.

In [735]:
F_diag_procedure = np.linalg.eig(F_prime)
F_diag_procedure

(array([-1.47689131, -0.34756791,  2.65409536,  0.17349941,  1.02190054,
         1.31430857,  0.74077138,  1.22295869,  1.80209034,  1.65425391]),
 array([[ 6.98631697e-01,  2.92547400e-01,  4.51456838e-02,
          1.74177734e-03,  5.00380177e-01, -4.17023120e-01,
         -4.60276053e-17,  7.61683187e-15,  6.17741226e-16,
         -4.22413415e-17],
        [ 5.77287568e-01,  1.67812482e-01,  2.30919072e-01,
          6.24628824e-02, -7.22741054e-01,  2.42895400e-01,
          5.91885150e-16, -6.23530866e-15,  3.55611384e-16,
          6.49829703e-16],
        [ 1.52463404e-16, -2.91924007e-16, -7.22434635e-16,
         -3.62079455e-16, -1.67465063e-15,  6.52148990e-16,
         -4.33065406e-01,  1.97199777e-01, -5.96175632e-01,
          6.46638399e-01],
        [ 3.46483870e-16, -1.03940471e-15, -1.99772648e-15,
         -1.18797387e-15,  1.16132817e-15, -2.57357206e-15,
         -3.50205774e-01, -2.44140411e-01,  7.38973487e-01,
          5.21219302e-01],
        [ 3.44824596e-02

In [736]:
#eigenvectormatrix_F = F_diag_procedure[1]
#print(eigenvectormatrix_F)

#F_prime_diagonalized = np.matmul(np.matrix.transpose(eigenvectormatrix_F),np.matmul(F_transformed,eigenvectormatrix_F))
#print(F_prime_diagonalized)

energy = 0
for i in range(0,overlap_integrals.shape[0]):
    for j in range(0,overlap_integrals.shape[0]):
        energy += 0.5*(P[i,j]*(H_core[i,j]+F[i,j]))

energy

-3.966069229883628

In [737]:
C_prime = np.matmul(X,F_diag_procedure[1])
print(C_prime)

[[ 5.91914124e-01  2.30601789e-01  4.28449894e-03  2.10387126e-02
   9.52128763e-01 -6.88755633e-01 -1.76781310e-15  1.20345950e-14
   1.32154266e-15 -1.52203440e-16]
 [ 4.08103985e-01  5.17777691e-01  8.84157727e-01 -1.58565906e-01
  -1.54019235e+00  4.27503825e-01 -2.23975848e-16 -1.34872287e-14
   1.59904454e-15  1.74042109e-15]
 [ 2.36927823e-16  2.65769889e-16 -8.83405241e-16 -7.98621660e-17
  -1.45570354e-15  6.59905774e-16 -3.07345696e-01  1.85723169e-01
  -6.55009651e-01  6.82402468e-01]
 [ 1.18425996e-15  7.90157938e-16 -2.51654423e-15 -2.16393924e-16
   1.09939542e-15 -2.57699963e-15 -2.48538212e-01 -2.29919496e-01
   8.11905489e-01  5.50049793e-01]
 [ 2.43455054e-02 -2.10354823e-02  1.30975668e+00 -9.92771840e-02
   1.58088725e-01  3.19460308e-01 -1.31440413e-15 -5.10625580e-15
  -1.71871451e-16  4.50178374e-16]
 [ 1.86509134e-01 -5.71717726e-01 -7.28650499e-01 -1.17710888e+00
  -5.88893758e-02 -2.27008806e-01  5.20734332e-15  6.40965549e-15
  -1.79078946e-15 -1.55288556e-15

In [738]:
P_new = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))

for i in range(0,overlap_integrals.shape[0]):
    for j in range(0,overlap_integrals.shape[1]):    
        for a in range(0,mol.nelectron//2):
            P_new[i,j]+=2*C_prime[i,a]*C_prime[j,a]
    
print(P_new)

[[ 7.00724660e-01  4.83125026e-01  2.80481850e-16  1.40196040e-15
   2.88208971e-02  2.20794781e-01 -7.60851486e-03  4.28849134e-16
   1.79213605e-15 -4.91918149e-02]
 [ 4.83125026e-01  3.33097726e-01  1.93382378e-16  9.66602422e-16
   1.98709956e-02  1.52230241e-01 -5.24580359e-03  2.95676406e-16
   1.23561482e-15 -3.39160275e-02]
 [ 2.80481850e-16  1.93382378e-16  1.12269587e-31  5.61168270e-31
   1.15362552e-17  8.83784060e-17 -3.04549054e-18  1.71657150e-31
   7.17345432e-31 -1.96902036e-17]
 [ 1.40196040e-15  9.66602422e-16  5.61168270e-31  2.80494332e-30
   5.76628148e-17  4.41750599e-16 -1.52225790e-17  8.58011052e-31
   3.58557920e-30 -9.84195080e-17]
 [ 2.88208971e-02  1.98709956e-02  1.15362552e-17  5.76628148e-17
   1.18540727e-03  9.08131825e-03 -3.12939213e-04  1.76386211e-17
   7.37107904e-17 -2.02326579e-03]
 [ 2.20794781e-01  1.52230241e-01  8.83784060e-17  4.41750599e-16
   9.08131825e-03  6.95713138e-02 -2.39740438e-03  1.35128184e-16
   5.64692965e-16 -1.55000910e-02

In [739]:
P = P_new