In [1]:
import numpy as np

In [2]:
from pyscf import gto, scf, df

In [8]:
#mol = gto.M(atom='H 0 0 0; H 0 0 0.740848149', basis='STO-3G', charge = 0)
mol = gto.M(atom='He 0 0 0; H 0 0 1', basis='def2-TZVP', charge = 1)


In [9]:
#get one elctron integrals

overlap_integrals = mol.intor('int1e_ovlp_sph')
print("overlap_integrals")
print(overlap_integrals)

kinetic_energy_integrals = mol.intor('int1e_kin_sph')
print("kinetic_energy_integrals")
print(kinetic_energy_integrals)

nuclear_attraction_integrals = mol.intor('int1e_nuc_sph')
print("nuclear_attraction_integrals")
print(nuclear_attraction_integrals)


overlap_integrals
[[ 1.00000000e+00  6.80510265e-01  3.28631854e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  2.85554679e-02  1.35743979e-01
   1.27240444e-01  0.00000000e+00  0.00000000e+00 -1.74133233e-01]
 [ 6.80510265e-01  1.00000000e+00  7.51586260e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.49146984e-01  3.58995975e-01
   3.46426369e-01  0.00000000e+00  0.00000000e+00 -3.96545956e-01]
 [ 3.28631854e-01  7.51586260e-01  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  2.96009974e-01  5.97096440e-01
   6.73792609e-01  0.00000000e+00  0.00000000e+00 -3.16036515e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  2.01358561e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  2.01358561e-01  0.0

In [10]:
#get two electron integrals

two_electron_integrals = mol.intor('int2e_sph')
print("two_electron_integrals")
print(two_electron_integrals)

two_electron_integrals
[[[[ 2.39512423e+00  1.34741764e+00  6.14184995e-01 ...  0.00000000e+00
     0.00000000e+00 -3.18176686e-01]
   [ 1.34741764e+00  1.35847059e+00  8.42764572e-01 ...  0.00000000e+00
     0.00000000e+00 -4.52511570e-01]
   [ 6.14184995e-01  8.42764572e-01  7.67081570e-01 ...  0.00000000e+00
     0.00000000e+00 -3.26274911e-01]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  4.82856640e-01
     0.00000000e+00 -0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     4.82856640e-01 -0.00000000e+00]
   [-3.18176686e-01 -4.52511570e-01 -3.26274911e-01 ... -0.00000000e+00
    -0.00000000e+00  6.09433008e-01]]

  [[ 1.34741764e+00  7.98799197e-01  3.68684853e-01 ...  0.00000000e+00
     0.00000000e+00 -1.92047018e-01]
   [ 7.98799197e-01  8.63928714e-01  5.47073923e-01 ...  0.00000000e+00
     0.00000000e+00 -2.94486718e-01]
   [ 3.68684853e-01  5.47073923e-01  5.10297471e-01 ...  0.00000000e+00
     0.00000000e+00 -2.1

In [11]:
#calculate core hamiltonian

H_core = kinetic_energy_integrals + nuclear_attraction_integrals
H_core

array([[-0.97836716, -2.38548738, -1.48347761,  0.        ,  0.        ,
        -0.04335083, -0.2108273 , -0.66227611, -0.61962883,  0.        ,
         0.        ,  0.85543619],
       [-2.38548738, -2.2016932 , -1.75894473,  0.        ,  0.        ,
        -0.14833472, -0.49437535, -0.943522  , -0.88938987,  0.        ,
         0.        ,  0.91767769],
       [-1.48347761, -1.75894473, -1.70812163,  0.        ,  0.        ,
        -0.15449945, -0.68931823, -1.11637808, -1.11493484,  0.        ,
         0.        ,  0.69092229],
       [ 0.        ,  0.        ,  0.        , -0.11983422,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.30982452,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.11983422,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.30982452,  0.        ],
       [-0.04335083, -0.14833472, -0.15449945,  0.        ,  0.        ,
        -0.2294278 , -

In [12]:
#diagonalize overlap integral matrix

overlap_diag_procedure = np.linalg.eigh(overlap_integrals)
overlap_diag_procedure

(array([0.08175764, 0.11062266, 0.21920965, 0.51406601, 0.74378799,
        0.79864144, 0.79864144, 1.20135856, 1.20135856, 1.34787755,
        1.65173276, 3.33094574]),
 array([[-1.89519862e-01,  2.15743553e-01, -3.40341427e-01,
          2.97793947e-01, -6.29871310e-01,  8.12759071e-16,
         -1.26923687e-16,  5.66676704e-31, -1.35546524e-16,
          1.24322199e-01,  4.86251281e-01, -2.53750340e-01],
        [ 4.52257972e-01, -4.45541481e-01,  4.41435527e-01,
         -1.40153365e-01, -6.32957047e-02,  1.89875786e-16,
         -2.18575277e-17, -3.13254095e-18, -1.03864663e-16,
          9.95716798e-02,  4.46905995e-01, -4.10854465e-01],
        [-3.12003400e-01,  6.02657468e-01,  3.20498010e-01,
         -1.51846647e-01,  3.82649091e-01, -7.15155387e-16,
          7.62402288e-17, -1.08263232e-16,  1.89425850e-16,
          1.59181148e-01,  1.36737172e-01, -4.72467414e-01],
        [ 0.00000000e+00,  2.77555756e-16,  0.00000000e+00,
         -1.11022302e-16,  9.99200722e-16,  6.9

In [14]:
#diagonalize overlap integral matrix

U = overlap_diag_procedure[1]
print(U)

#print(np.matmul(overlap_integrals,U))
#print(np.matrix.transpose(U))

#rint("---------------")

# = np.matmul(np.matrix.transpose(U),np.matmul(overlap_integrals,U))
#print(s)

s_inverse = np.diag(1/overlap_diag_procedure[0])
s_inverse

[[-1.89519862e-01  2.15743553e-01 -3.40341427e-01  2.97793947e-01
  -6.29871310e-01  8.12759071e-16 -1.26923687e-16  5.66676704e-31
  -1.35546524e-16  1.24322199e-01  4.86251281e-01 -2.53750340e-01]
 [ 4.52257972e-01 -4.45541481e-01  4.41435527e-01 -1.40153365e-01
  -6.32957047e-02  1.89875786e-16 -2.18575277e-17 -3.13254095e-18
  -1.03864663e-16  9.95716798e-02  4.46905995e-01 -4.10854465e-01]
 [-3.12003400e-01  6.02657468e-01  3.20498010e-01 -1.51846647e-01
   3.82649091e-01 -7.15155387e-16  7.62402288e-17 -1.08263232e-16
   1.89425850e-16  1.59181148e-01  1.36737172e-01 -4.72467414e-01]
 [ 0.00000000e+00  2.77555756e-16  0.00000000e+00 -1.11022302e-16
   9.99200722e-16  6.92313874e-01 -1.43880156e-01  3.34230723e-01
  -6.23129058e-01  3.88578059e-16 -2.22044605e-16 -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.11022302e-16
   0.00000000e+00 -1.43880156e-01 -6.92313874e-01  6.23129058e-01
   3.34230723e-01  6.10622664e-16 -5.55111512e-17  0.00000000e+00]
 [ 1.

array([[12.23127241,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  9.03973941,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  4.56184303,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.94527546,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.34446913,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.25212636,  

In [15]:
#take square root of diagonalized overlap integral matrix

s_inverse_sqrt = s_inverse**0.5
s_inverse_sqrt

array([[3.49732361, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 3.00661594, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 2.13584715, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.39473132, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.15951246,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.11898452, 0.        , 0.        , 0.        , 0.        ,
        0.        ,

In [16]:
#obtain transformation matrix X

test = np.matmul(s_inverse_sqrt,np.matrix.transpose(U))
print(test)
X = np.matmul(U,np.matmul(s_inverse_sqrt,np.matrix.transpose(U)))
print(X)

[[-6.62812287e-01  1.58169248e+00 -1.09117686e+00  0.00000000e+00
   0.00000000e+00  3.99305057e-01  9.13745593e-01 -2.06256377e+00
   1.64695513e+00 -6.65641133e-18  5.83146270e-17  3.72193757e-01]
 [ 6.48658006e-01 -1.33957212e+00  1.81195955e+00  8.34503561e-16
   0.00000000e+00  5.66084508e-01  6.44822158e-01 -1.60663836e+00
   1.38759144e-01 -1.99683063e-16 -1.16861940e-17  4.52264467e-01]
 [-7.26917265e-01  9.42838810e-01  6.84534761e-01  0.00000000e+00
   0.00000000e+00  7.99580752e-01 -3.08829003e-01  6.38838463e-02
  -9.22517562e-01 -3.17568203e-17 -6.95168246e-17  1.04215015e+00]
 [ 4.15342545e-01 -1.95476288e-01 -2.11785275e-01 -1.54846283e-16
   1.54846283e-16  6.22159906e-01 -8.56548942e-01  1.36542270e-01
   6.16808179e-01  6.43200667e-17 -1.02889075e-16  4.12124848e-01]
 [-7.30343629e-01 -7.33921580e-02  4.43686387e-01  1.15858568e-15
   0.00000000e+00 -1.92942902e-01 -5.12276957e-01 -8.40812536e-02
   3.84888795e-01 -9.09307421e-16 -5.23890484e-19 -3.92376876e-01]
 [ 9.

In [17]:
#recheck XtrSX - works OK
test = np.matmul(np.matrix.transpose(X),np.matmul(overlap_integrals,X))
test

array([[ 1.00000000e+00, -7.57322284e-16,  4.50581889e-16,
         1.08437222e-16,  2.08775397e-17,  8.33754202e-17,
         2.34185208e-16,  5.98824907e-16,  2.28983499e-16,
        -5.38475012e-18,  6.29080528e-19, -8.18789481e-16],
       [-9.12224353e-16,  1.00000000e+00,  5.14604498e-16,
        -3.32199157e-16, -3.21910800e-17,  3.60444975e-16,
         1.01134251e-15,  4.02222690e-16,  1.70696790e-15,
         1.21460579e-17,  1.18218261e-17,  9.15933995e-16],
       [ 5.56985525e-16,  4.84931585e-16,  1.00000000e+00,
         4.02464626e-16,  1.27065231e-16, -1.39334861e-16,
        -3.81520135e-16,  1.29407435e-15, -2.55351296e-15,
        -1.63135984e-17, -6.04123849e-17, -2.22044605e-16],
       [ 1.08437222e-16, -3.32199157e-16,  4.02464626e-16,
         1.00000000e+00, -9.87366848e-17,  1.38683435e-16,
        -3.52585699e-17, -8.76235941e-17, -1.03903500e-17,
         3.32263449e-16, -7.43890260e-17,  6.99891207e-17],
       [ 2.08775397e-17, -3.21910800e-17,  1.2706523

In [18]:
#intitial guess for density matrix

P = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))
P

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
# calculate G matrix

G = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))

#for i in range(0,two_electron_integrals.shape[0]):
#    for j in range(0,two_electron_integrals.shape[1]):
#        for k in range(0,two_electron_integrals.shape[2]):
#            for l in range(0,two_electron_integrals.shape[3]):
#                print(two_electron_integrals[i,j,k,l])

#print("-------------")
                
                
for i in range(0,two_electron_integrals.shape[0]):
    for j in range(0,two_electron_integrals.shape[1]):
        for k in range(0,two_electron_integrals.shape[2]):
            for l in range(0,two_electron_integrals.shape[3]):
                G[i,j]+=P[k,l]*(two_electron_integrals[i,j,k,l]-0.5*two_electron_integrals[i,l,k,j])
#print(G)

F = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))
F = H_core + G
print(F)

[[ 9.55348587e-01 -1.52443959e+00 -1.23820315e+00  2.50587382e-17
  -1.09697199e-17 -8.44780700e-02 -2.75752804e-01 -6.20270489e-01
  -5.72462915e-01  3.95889348e-18  2.01438520e-21  7.42135141e-01]
 [-1.52443959e+00 -1.02627442e+00 -9.86627756e-01  1.70172217e-17
  -7.45306366e-18 -1.76528112e-01 -4.05375113e-01 -6.21374355e-01
  -5.70992154e-01  2.28264704e-18  1.04025994e-18  4.97645372e-01]
 [-1.23820315e+00 -9.86627756e-01 -7.47392897e-01  9.78498967e-18
  -4.25508538e-18 -1.71863328e-01 -4.29958800e-01 -5.77172213e-01
  -5.23695338e-01 -7.61507874e-19  1.77597544e-18  3.41074346e-01]
 [ 2.50587382e-17  1.70172217e-17  9.78498967e-18  1.60106591e+00
   5.48481759e-34  2.14284941e-18  4.75478727e-18  6.64769559e-18
   5.10341191e-18 -2.12429648e-02 -1.56730616e-35 -7.16753236e-18]
 [-1.09697199e-17 -7.45306366e-18 -4.25508538e-18  5.48481759e-34
   1.60106591e+00 -9.13358323e-19 -1.96775833e-18 -2.79660147e-18
  -2.16971982e-18  7.23205035e-35 -2.12429648e-02  3.12693982e-18]
 [-8.

In [27]:
F_prime = np.matmul(np.matrix.transpose(X),np.matmul(F,X))
F_prime

array([[ 3.57976848e+00, -3.34361116e+00, -7.82803784e-02,
         5.03522620e-16,  7.66084020e-17, -1.09803657e-01,
         5.79294490e-02, -9.28147632e-02, -2.14014054e-01,
        -7.57108331e-17, -4.99002985e-18,  1.81407912e-01],
       [-3.34361116e+00,  2.00926502e+00, -8.60240045e-01,
        -6.99608264e-16, -1.15695373e-16,  1.55424364e-01,
        -1.41445568e-01, -3.60773724e-01,  1.76830708e-02,
         1.08921165e-16,  3.57582435e-17,  5.79239397e-01],
       [-7.82803784e-02, -8.60240045e-01,  2.07119069e-01,
         6.12240211e-16,  1.68662006e-16,  2.87787125e-01,
        -1.77133926e-01, -1.49689414e-01, -1.80084096e-01,
        -1.23195523e-16, -8.44154603e-17,  3.65607478e-01],
       [ 5.03522620e-16, -6.99608264e-16,  6.12240211e-16,
         1.66752201e+00, -1.32628426e-16,  3.09061960e-16,
        -6.08828812e-17, -1.35329458e-16, -7.58165428e-17,
        -3.02500355e-01, -7.12239698e-17,  1.44000646e-16],
       [ 7.66084020e-17, -1.15695373e-16,  1.6866200

In [28]:
F_diag_procedure = np.linalg.eigh(F_prime)
F_diag_procedure

(array([-1.36725279, -0.35329628,  0.02304761,  0.55596126,  0.99084613,
         0.99084613,  1.26659276,  1.8027514 ,  1.8027514 ,  1.97404136,
         2.72243311,  6.29664044]),
 array([[ 4.56313923e-01, -1.69768850e-01, -5.28077439e-03,
         -3.69838966e-01, -1.13716728e-16, -1.20572504e-16,
         -1.32446487e-01, -2.93299333e-16,  1.20824404e-16,
         -6.45008142e-02, -1.02846530e-01, -7.70628028e-01],
        [ 6.36459769e-01, -2.37458473e-01,  3.69584472e-02,
         -3.39139815e-01, -6.19729063e-17, -1.72306892e-16,
         -1.52224769e-01, -6.98010989e-17, -7.40404137e-17,
         -6.70113101e-02, -2.94680974e-02,  6.27390971e-01],
        [ 4.72010782e-01, -1.32208299e-01, -1.21747178e-01,
          8.39100204e-01,  1.13451732e-16, -1.59073676e-17,
         -1.66061768e-02,  4.78734697e-16,  3.26388779e-16,
          6.93832750e-02, -1.74375566e-01, -7.29288512e-02],
        [ 4.21353409e-17,  1.24074320e-16,  4.75070770e-17,
         -2.97344150e-16,  2.973318

In [29]:
#eigenvectormatrix_F = F_diag_procedure[1]
#print(eigenvectormatrix_F)

#F_prime_diagonalized = np.matmul(np.matrix.transpose(eigenvectormatrix_F),np.matmul(F_transformed,eigenvectormatrix_F))
#print(F_prime_diagonalized)

energy = 0
for i in range(0,overlap_integrals.shape[0]):
    for j in range(0,overlap_integrals.shape[0]):
        energy += 0.5*(P[i,j]*(H_core[i,j]+F[i,j]))

energy

-3.8584782243861246

In [30]:
C_prime = np.matmul(X,F_diag_procedure[1])
print(C_prime)

[[ 2.58648682e-01 -9.60673418e-02 -3.58313652e-03 -1.19177393e-01
  -5.92647503e-17 -3.32336102e-17 -5.77892225e-02 -1.65187868e-16
   2.30240236e-16 -5.39583773e-03 -7.72755174e-02 -1.47263617e+00]
 [ 5.16247014e-01 -1.80638173e-01 -1.68157766e-02 -1.14842283e+00
  -2.45322601e-16 -3.60383741e-16 -3.04715240e-01 -8.21925707e-16
  -7.98521548e-16 -3.59505026e-01 -1.25592093e-01  1.88455042e+00]
 [ 2.68247047e-01 -5.01953314e-01  7.28759057e-02  1.94864865e+00
   3.73244616e-16 -4.91618953e-17 -4.99305240e-02  1.30933438e-15
   7.83241015e-16  1.03475929e-01 -7.39797408e-01 -7.70934766e-01]
 [ 3.03948020e-17  8.46468502e-17  3.50455617e-18 -8.29269596e-18
   2.33274662e-01 -2.19328874e-01 -5.52250696e-16  5.82861292e-01
  -7.74602576e-01  1.78162680e-15 -7.43274668e-16 -4.33067646e-16]
 [ 1.18527153e-17 -2.18915353e-16  3.99101966e-17 -1.17959717e-16
   2.19328874e-01  2.33274662e-01  6.84064145e-16  7.74602576e-01
   5.82861292e-01 -3.52776280e-15  5.84575713e-16 -9.77546099e-17]
 [ 3.

In [31]:
P_new = np.zeros((overlap_integrals.shape[0], overlap_integrals.shape[0]))

for i in range(0,overlap_integrals.shape[0]):
    for j in range(0,overlap_integrals.shape[1]):    
        for a in range(0,mol.nelectron//2):
            P_new[i,j]+=2*C_prime[i,a]*C_prime[j,a]
    
print(P_new)

[[ 1.33798281e-01  2.67053219e-01  1.38763490e-01  1.57231509e-17
   6.13137835e-18  1.55538354e-02  4.24882996e-02  5.80122471e-02
  -8.09408727e-03 -7.14455506e-19 -2.50244395e-18 -1.84458187e-02]
 [ 2.67053219e-01  5.33021959e-01  2.76963474e-01  3.13824515e-17
   1.22378577e-17  3.10445081e-02  8.48040580e-02  1.15788912e-01
  -1.61553052e-02 -1.42600967e-18 -4.99472571e-18 -3.68167306e-02]
 [ 1.38763490e-01  2.76963474e-01  1.43912957e-01  1.63066318e-17
   6.35891174e-18  1.61310330e-02  4.40650261e-02  6.01650621e-02
  -8.39445613e-03 -7.40968710e-19 -2.59530881e-18 -1.91303368e-02]
 [ 1.57231509e-17  3.13824515e-17  1.63066318e-17  1.84768797e-33
   7.20521867e-34  1.82779106e-18  4.99296360e-18  6.81724241e-18
  -9.51167345e-19 -8.39584161e-35 -2.94071820e-34 -2.16763915e-18]
 [ 6.13137835e-18  1.22378577e-17  6.35891174e-18  7.20521867e-34
   2.80973718e-34  7.12762893e-19  1.94704923e-18  2.65844250e-18
  -3.70915913e-19 -3.27403087e-35 -1.14675843e-34 -8.45289587e-19]
 [ 1.

In [32]:
P = P_new